# Generated by Django 5.0.2 on 2025-11-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
    ]
