# Generated by Django 5.2.8 on 2025-11-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='id',
        ),
        migrations.AddField(
            model_name='evento',
            name='idEvento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
